### ISSUE TITLE
pybedtools.cbedtools.MalformedBedLineError: Start is greater than stop

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#100]
I tried to run MetaSV with the following command: 

run_metasv.py --reference ../../../../../mnt/data/GRCh37_bcgsc/GRCh37-lite.fa --boost_ins --breakdancer_native ../../breakdancer/perl/A10898_breakdancer --breakseq_native ../../work/breakseq.gff --cnvnator_native ../../CNVnator_v0.3.2/src/A10898_100_cnvnator --pindel_native ../../pindel-master/A10898_D ../../pindel-master/A10898_LI ../../pindel-master/A10898_SI ../../pindel-master/A10898_TD ../../pindel-master/A10898_INV --sample A10898 --bam ../../../../mnt/data/A10898_3_lanes_dupsFlagged.bam --spades ../../SPAdes-3.6.2-Linux/bin/spades.py --age ../../AGE-simple-parseable-output/age_align --num_threads 15 --workdir A10898_work_metaSV --outdir A10898_out_metaSV --min_ins_support 2 --max_ins_intervals 500000 --isize_mean 500 --isize_sd 150

Eventually I get this traceback: 
Traceback (most recent call last):
  File "/usr/local/bin/run_metasv.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/hpcuser01/metasv-0.3/scripts/run_metasv.py", line 108, in <module>    stop_spades_on_fail=args.stop_spades_on_fail, gt_window=args.gt_window, gt_normal_frac=args.gt_normal_frac, isize_mean=args.isize_mean, isize_sd=args.isize_sd, extraction_max_read_pairs=args.extraction_max_read_pairs))
  File "/home/hpcuser01/metasv-0.3/metasv/main.py", line 327, in run_metasv
    min_support_frac=min_support_frac, max_intervals=max_intervals)
  File "/home/hpcuser01/metasv-0.3/metasv/generate_sv_intervals.py", line 243, in parallel_generate_sc_intervals
    "Merging %d features with %d features from %s" % (bedtool.count(), skip_bedtool.count(), skip_bed))
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 2261, in count
    return sum(1 for _ in iter(self))
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 2261, in <genexpr>
    return sum(1 for _ in iter(self))
  File "pybedtools/cbedtools.pyx", line 772, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:11001)
  File "pybedtools/cbedtools.pyx", line 682, in pybedtools.cbedtools.create_interval_from_list (pybedtools/cbedtools.cxx:9798)
pybedtools.cbedtools.MalformedBedLineError: Start is greater than stop

Prior to this message, I was getting errors for each chromosomes: 
Traceback (most recent call last):
  File "/home/hpcuser01/metasv-0.3/metasv/generate_sv_intervals.py", line 148, in generate_sc_intervals
    filtered_bed)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 775, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 2912, in moveto
    fn = self._collapse(self, fn=fn)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 1215, in _collapse
    for i in iterable:
  File "pybedtools/cbedtools.pyx", line 731, in pybedtools.cbedtools.IntervalIterator.__next__ (pybedtools/cbedtools.cxx:10588)
    line = next(self.stream)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools-0.7.4-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 876, in _generator
    result = func(f, *args, **kwargs)
  File "/home/hpcuser01/metasv-0.3/metasv/generate_sv_intervals.py", line 90, in merged_interval_features
    interval_readcount = bam_handle.count(reference=feature.chrom, start=feature.start, end=feature.end)
  File "csamtools.pyx", line 1169, in pysam.csamtools.Samfile.count (pysam/csamtools.c:13478)
  File "csamtools.pyx", line 989, in pysam.csamtools.Samfile._parseRegion (pysam/csamtools.c:11668)
  File "csamtools.pyx", line 923, in pysam.csamtools.Samfile.gettid (pysam/csamtools.c:10827)
  File "csamtools.pyx", line 57, in pysam.csamtools._force_bytes (pysam/csamtools.c:3393)
TypeError: Expected bytes, got unicode

I'm not sure what the issue is. Your help would be appreciated!

Thanks, 
Madeline

**Comment by marghoob** [comment]
Hi @Madelinehazel 
Some of the issues you mention have been fixed in later releases. Could you please try installing from the master branch and let me know how it goes? The "Expected bytes, got unicode" error was due to using a more recent version of pybedtools (the bug should be fixed in the master branch).

Thanks.

**Comment by Madelinehazel** [comment]
I cloned the metasv repo and attempted to install using $python ez_setup.py
I got the following error: 
Extracting in /tmp/tmpDSRfHm
Now working in /tmp/tmpDSRfHm/setuptools-12.0.4
Installing Setuptools
running install
Traceback (most recent call last):
  File "setup.py", line 179, in <module>
    dist = setuptools.setup(**setup_params)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/tmpDSRfHm/setuptools-12.0.4/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/tmp/tmpDSRfHm/setuptools-12.0.4/setuptools/command/install.py", line 103, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/tmp/tmpDSRfHm/setuptools-12.0.4/setuptools/command/easy_install.py", line 304, in finalize_options
    self.check_site_dir()
  File "/tmp/tmpDSRfHm/setuptools-12.0.4/setuptools/command/easy_install.py", line 428, in check_site_dir
    self.cant_write_to_target()
  File "/tmp/tmpDSRfHm/setuptools-12.0.4/setuptools/command/easy_install.py", line 486, in cant_write_to_target
    msg = self._cant_write_msg % (sys.exc_info()[1], self.install_dir,)
  File "/usr/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: _cant_write_msg
Something went wrong during the installation.
See the error message above.
Is there another way to install?

Thanks for replying so quickly.

**Comment by marghoob** [comment]
Try using this: pip install
https://github.com/bioinform/metasv/archive/master.zip

**Comment by Madelinehazel** [comment]
It successfully installs, but says "Successfully installed MetaSV--0.3-" This is the old version, I thought.

**Comment by marghoob** [comment]
Please uninstall first using pip uninstall metav and try it again. After
installing MetaSV, you can run run_metasv.py --version to check the version.

**Comment by Madelinehazel** [comment]
That worked, thank you!
