### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#103]
Hello, 

I've run MetaSV and received this following message:
________________________________________________________________
ERROR 2016-02-23 02:20:01,971 run_spades_single-<Process(PoolWorker-15, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metasv/run_spades.py", line 75, in run_spades_single
    retcode = cmd.run(cmd_log_fd_out=spades_log_fd, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/metasv/external_cmd.py", line 20, in run
    self.p = subprocess.Popen(self.cmd, stderr=cmd_log_fd_err, stdout=cmd_log_fd_out)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
()
INFO 2016-02-23 02:20:07,528 metasv.run_spades    Merging the contigs from []
________________________________________________________________

I am running on a machine with 96 GB of RAM, so memory shouldn't be an issue here. Monitoring RAM during while the script is running, it seems to use about 55 GB RAM. Have you an idea what the issue might be? 

Thanks again for your assistance, 
Madeline

**Comment by marghoob** [comment]
Can you post the full command-line here?

**Comment by Madelinehazel** [comment]
[hpcuser01@friedmanhpc03:/]> python /usr/local/bin/run_metasv.py --reference mnt/data/GRCh37_bcgsc/GRCh37-lite.fa --breakdancer_native home/hpcuser01/breakdancer/perl/A10898_breakdancer --breakseq_native home/hpcuser01/work/breakseq.gff --cnvnator_native home/hpcuser01/CNVnator_v0.3.2/src/A10898_100_cnvnator --pindel_native home/hpcuser01/pindel-master/A10898_D home/hpcuser01/pindel-master/A10898_LI home/hpcuser01/pindel-master/A10898_SI home/hpcuser01/pindel-master/A10898_TD home/hpcuser01/pindel-master/A10898_INV --sample A10898 --bam mnt/data/A10898_3_lanes_dupsFlagged.bam --spades home/hpcuser01/SPAdes-3.6.2-Linux/bin/spades.py --age home/hpcuser01/AGE-simple-parseable-output/age_align --num_threads 15 --workdir mnt/data/A10898_work --outdir mnt/data/A10898_out --min_support_ins 2 --max_ins_intervals 500000 --isize_mean 500 --isize_sd 150

**Comment by marghoob** [comment]
You can try running with fewer threads (--num_threads 10 ?) since that will
require lesser memory. In the worst case, it should work with 2 threads (if
it doesn't then the machine may be too loaded).

**Comment by Madelinehazel** [comment]
I tried the above with 2 threads, and eventually got these error messages:

INFO 2016-03-22 07:07:43,216 run_age_single-<Process(PoolWorker-3, started daemon)> Returned code 0 (0.129607 seconds)
ERROR 2016-03-22 07:07:43,233 run_age_single-<Process(PoolWorker-3, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metasv/run_age.py", line 151, in run_age_single
    age_record = AgeRecord(out,tr_region_1=tr_region)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 85, in __init__
    self.read_from_age_file(age_out_file)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 186, in read_from_age_file
    file2, len2 = self.parse_input_descriptor(age_fd)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 126, in parse_input_descriptor
    raise AgeFormatError("INPUT DESCRIPTOR", age_fd.line_num)
AgeFormatError: Error while reading AGE output, L21 (section INPUT DESCRIPTOR).
()
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 380, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 3 arguments (1 given)', <class 'metasv.age_parser.AgeFormatError'>, ())

INFO 2016-03-22 07:07:43,657 run_age_single-<Process(PoolWorker-4, started daemon)> Returned code 0 (0.112007 seconds)
ERROR 2016-03-22 07:07:43,659 run_age_single-<Process(PoolWorker-4, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metasv/run_age.py", line 151, in run_age_single
    age_record = AgeRecord(out,tr_region_1=tr_region)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 85, in __init__
    self.read_from_age_file(age_out_file)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 186, in read_from_age_file
    file2, len2 = self.parse_input_descriptor(age_fd)
  File "/usr/local/lib/python2.7/dist-packages/metasv/age_parser.py", line 126, in parse_input_descriptor
    raise AgeFormatError("INPUT DESCRIPTOR", age_fd.line_num)
AgeFormatError: Error while reading AGE output, L21 (section INPUT DESCRIPTOR).
()

Do you know what the problem might be? Thank you.

**Comment by marghoob** [comment]
Hi Madeline

Which version of MetaSV are you using? Please try to install from the (to
be 0.5.3) branch fix-sc-interval-merging using "pip install -U --no-deps
https://github.com/bioinform/metasv/archive/fix-sc-interval-merging.zip".
Also, please use AGE binary obtained by building from
https://github.com/abyzovlab/AGE using "make OMP=no". This change is
because we switched to using the original AGE output instead of the
modified AGE from my fork.

Hope that helps,
Marghoob.

**Comment by barrykui** [comment]
Hi, @Madelinehazel , have you solved this problem?
I received the same error, details as follows:
```
Traceback (most recent call last):
  File "seqnet.py", line 442, in <module>
    main()
  File "seqnet.py", line 161, in main
    train_val_test()
  File "seqnet.py", line 429, in train_val_test
    train_model_runner(n)
  File "seqnet.py", line 292, in train_model_runner
    plot(model, to_file=bestModelName+"."+str(n)+".str.png")
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/visualize_util.py", line 74, in plot
    dot.write(to_file, format=format)
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1911, in write
    dot_fd.write(self.create(prog, format))
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1990, in create
    stderr=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory           
```
