### ISSUE TITLE
Permissions errors during run_spades_single in run_spades.py 

### ISSUE THREAD

**Issue by aktilot** [bioinform/metasv#108]
Hi and thanks in advance for your help!

While running MetaSV, it got stuck while running spades. There are a few 'OSError: [Errno 13] Permission denied' errors during the run_spades_single process, and then it seems to hang while merging the contigs. The merged.fa and spades.log files are both empty. Running MetaSV on the same sample with --disable_assembly went fine with no errors. The error messages are below, please let me know if there is anything I should try or additional information that would be helpful. 

Thanks!

Amanda

Errors: 
INFO 2016-04-06 14:10:19,200 extract_read_pairs-<Process(PoolWorker-7, started daemon)> Examined 256 pairs in 11.3396 seconds
INFO 2016-04-06 14:10:19,200 extract_read_pairs-<Process(PoolWorker-7, started daemon)> Extraction counts [('all_pair_hq', 256), ('non_perfect_hq', 107)]
INFO 2016-04-06 14:10:19,202 run_spades_single-<Process(PoolWorker-7, started daemon)> Running /HOME/BIOINFORMATICS/SOFTWARE/SPADES-3.7.1-LINUX/BIN/ with arguments ['-1', 'work/spades/2/_all_pair_hq_1.fq', '-2', 'work/spades/2/_all_pair_hq_2.fq', '-o', 'work/spades/2/spades_all_pair_hq/', '-m', '4', '-t', '1', '--phred-offset', '33']
ERROR 2016-04-06 14:10:19,950 run_spades_single-<Process(PoolWorker-7, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/home/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 75, in run_spades_single
    retcode = cmd.run(cmd_log_fd_out=spades_log_fd, timeout=timeout)
  File "/home/.local/lib/python2.7/site-packages/metasv/external_cmd.py", line 20, in run
    self.p = subprocess.Popen(self.cmd, stderr=cmd_log_fd_err, stdout=cmd_log_fd_out)
  File "/usr/local/apps/python-2.7.11/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/apps/python-2.7.11/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
INFO 2016-04-06 14:10:20,589 metasv.run_spades    Merging the contigs from []
^CTraceback (most recent call last):
  File "/home/Bioinformatics/software/metasv/scripts/run_metasv.py", line 143, in <module>
    sys.exit(run_metasv(args))
  File "/home/.local/lib/python2.7/site-packages/metasv/main.py", line 306, in run_metasv
    assembly_max_tools=args.assembly_max_tools)
  File "/home/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 214, in run_spades_parallel
    for line in fileinput.input(assembly_fastas):
  File "/usr/local/apps/python-2.7.11/lib/python2.7/fileinput.py", line 254, in next
    line = self.readline()
  File "/usr/local/apps/python-2.7.11/lib/python2.7/fileinput.py", line 349, in readline
    self._buffer = self._file.readlines(self._bufsize)

**Comment by marghoob** [comment]
Did you check that spades.py is executable and runnable by you? Apologies for the delay since I am traveling currently.

**Comment by aktilot** [comment]
Hi Marghoob,

Apologies for the delay in responding, it's been a busy week leading up to a conference tomorrow. My plan is to get back to this error on when I return on Tuesday. In the meantime, the permissions should have been ok. Here they are, from SPAdes-3.7.1-Linux/bin/:

-rwxr-xr-x 1 4294967294 lag  48K Feb 19 04:32 spades.py

In case it helps, I had a few issues when installing MetaSV. Maybe my solution caused an issue with SPAdes. When I tried using pip to install MetaSV, I only ended up with the files in the metasv/metasv/ directory. If I downloaded and extracted the metasv-0.5.2.tar.gz file into my normal software directory, I ended up with the full set of files. In order to get MetaSV to run, I needed to do both of these steps, and run the 'run_metasv.py' file from the software directory after adding /metasv/scripts/ and /metasv/metasv/ to $PATH. I did make sure to add SPAdes, AGE, etc. to $PATH as well, before running MetaSV. 

Sorry if that's quite confusing, I can try to give a better explanation next week if you think it will be useful. 

Thanks for your help!

**Comment by aktilot** [comment]
Hi Marghoob,

I looked through everything again and I think there was an error on my part with SPAdes, it seems to run fine now. I've bumped into the same error that James posted about in March, but I will try the solutions you mentioned in that thread and post if there are still errors when generating the final vcf. 

Thanks again for your help,

Amanda

**Comment by marghoob** [comment]
Thanks, Amanda. Please let me know if the solution worked so that I can fix/close this bug.

Best
Marghoob

**Comment by JiaB-He** [comment]
> Hi and thanks in advance for your help!
> 
> While running MetaSV, it got stuck while running spades. There are a few 'OSError: [Errno 13] Permission denied' errors during the run_spades_single process, and then it seems to hang while merging the contigs. The merged.fa and spades.log files are both empty. Running MetaSV on the same sample with --disable_assembly went fine with no errors. The error messages are below, please let me know if there is anything I should try or additional information that would be helpful.
> 
> Thanks!
> 
> Amanda
> 
> Errors: INFO 2016-04-06 14:10:19,200 extract_read_pairs-<Process(PoolWorker-7, started daemon)> Examined 256 pairs in 11.3396 seconds INFO 2016-04-06 14:10:19,200 extract_read_pairs-<Process(PoolWorker-7, started daemon)> Extraction counts [('all_pair_hq', 256), ('non_perfect_hq', 107)] INFO 2016-04-06 14:10:19,202 run_spades_single-<Process(PoolWorker-7, started daemon)> Running /HOME/BIOINFORMATICS/SOFTWARE/SPADES-3.7.1-LINUX/BIN/ with arguments ['-1', 'work/spades/2/_all_pair_hq_1.fq', '-2', 'work/spades/2/_all_pair_hq_2.fq', '-o', 'work/spades/2/spades_all_pair_hq/', '-m', '4', '-t', '1', '--phred-offset', '33'] ERROR 2016-04-06 14:10:19,950 run_spades_single-<Process(PoolWorker-7, started daemon)> Caught exception in worker thread Traceback (most recent call last): File "/home/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 75, in run_spades_single retcode = cmd.run(cmd_log_fd_out=spades_log_fd, timeout=timeout) File "/home/.local/lib/python2.7/site-packages/metasv/external_cmd.py", line 20, in run self.p = subprocess.Popen(self.cmd, stderr=cmd_log_fd_err, stdout=cmd_log_fd_out) File "/usr/local/apps/python-2.7.11/lib/python2.7/subprocess.py", line 710, in **init** errread, errwrite) File "/usr/local/apps/python-2.7.11/lib/python2.7/subprocess.py", line 1335, in _execute_child raise child_exception OSError: [Errno 13] Permission denied INFO 2016-04-06 14:10:20,589 metasv.run_spades Merging the contigs from [] ^CTraceback (most recent call last): File "/home/Bioinformatics/software/metasv/scripts/run_metasv.py", line 143, in sys.exit(run_metasv(args)) File "/home/.local/lib/python2.7/site-packages/metasv/main.py", line 306, in run_metasv assembly_max_tools=args.assembly_max_tools) File "/home/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 214, in run_spades_parallel for line in fileinput.input(assembly_fastas): File "/usr/local/apps/python-2.7.11/lib/python2.7/fileinput.py", line 254, in next line = self.readline() File "/usr/local/apps/python-2.7.11/lib/python2.7/fileinput.py", line 349, in readline self._buffer = self._file.readlines(self._bufsize)

Hi, I encountered the same error as yours, please tell me how you solved it 


ERROR 2022-11-16 22:50:48,840 run_spades_single-<Process(PoolWorker-29, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/home/jbhe/software/anaconda3/envs/python27/lib/python2.7/site-packages/metasv/run_spades.py", line 75, in run_spades_single
    retcode = cmd.run(cmd_log_fd_out=spades_log_fd, timeout=timeout)
  File "/home/jbhe/software/anaconda3/envs/python27/lib/python2.7/site-packages/metasv/external_cmd.py", line 20, in run
    self.p = subprocess.Popen(self.cmd, stderr=cmd_log_fd_err, stdout=cmd_log_fd_out)
  File "/home/jbhe/software/anaconda3/envs/python27/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/home/jbhe/software/anaconda3/envs/python27/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
()
INFO 2022-11-16 22:50:48,894 metasv.run_spades    Merging the contigs from []
