### ISSUE TITLE
Insertion detection 

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/metasv#111]
Hello, 

When I try to run enhanced insertion detection, I get an error message. This is my command:

run_metasv.py --reference /mnt/data/GRCh37_bcgsc/GRCh37-lite.fa --boost_sc --sample A48018 --bam /mnt/data/A48018_2_lanes_dupsFlagged.bam --spades /home/hpcuser01/SPAdes-3.6.2-Linux/spades.py --age /home/hpcuser01/AGE/age_align --num_threads 50 --workdir A48018_work_boostins --outdir A48018_out_boostinst --max_ins_intervals 500000 --isize_mean 462 --isize_sd 119 --chromosomes X

And the error message:

ERROR 2016-06-24 11:59:42,265 run_spades_single-<Process(PoolWorker-51, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/metasv/run_spades.py", line 75, in run_spades_single
    retcode = cmd.run(cmd_log_fd_out=spades_log_fd, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/metasv/external_cmd.py", line 20, in run
    self.p = subprocess.Popen(self.cmd, stderr=cmd_log_fd_err, stdout=cmd_log_fd_out)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

What might be the issue here?

Also, the http://bioinform.github.io/metasv/ website should be updated for enhancing insertion detection (.e.g boost_ins is no longer an option). 

Thanks for your help, 
Madeline

**Comment by Chandralinjo** [comment]
Hi,

I know this thread is a year old now, but I have the same issue right now. Do you remember how did  you (if you did) fix it?

Thanks,
Boris

**Comment by Chandralinjo** [comment]
Turns out I was missing a '/' in my path to spades.py, it was evading me for a day and a half. So, if anyone else is having the same problem, triplecheck your paths!

Good luck!

**Comment by marghoob** [comment]
Thanks, I am glad it worked for you!
