### ISSUE TITLE
error in bed to output final vcf file

### ISSUE THREAD

**Issue by dauss75** [bioinform/metasv#112]
Hello,

I have been getting this error below when running metasv with soft-clip.  Have you seen this before?  I am using correct version of tools as listed in http://bioinform.github.io/metasv/. 

INFO 2016-08-31 22:00:33,727 genotype_intervals-<Process(PoolWorker-16, started daemon)> Genotyped 6 intervals in 0.0038044 minutes
INFO 2016-08-31 22:00:33,803 parallel_genotype_intervals-<_MainProcess(MainProcess, started)> Following BED files will be merged: ['work/genotyping/0/genotyped.bed', 'work/genotyping/1/genotyped.bed', 'work/genotyping/2/genotyped.bed', 'work/genotyping/3/genotyped.bed']
INFO 2016-08-31 22:00:33,845 parallel_genotype_intervals-<_MainProcess(MainProcess, started)> Finished parallel genotyping of 27 intervals in 0.00704072 minutes
INFO 2016-08-31 22:00:33,847 metasv.main          Output final VCF file
feature.field:0/1
Traceback (most recent call last):
  File "/mnt/galaxyTools/tools/pymodules/python2.7/bin/run_metasv.py", line 146, in <module>
    sys.exit(run_metasv(args))
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/MetaSV-0.5-py2.7.egg/metasv/main.py", line 335, in run_metasv
    convert_metasv_bed_to_vcf(bedfile=genotyped_bed, vcf_out=final_vcf, workdir=args.workdir, sample=args.sample, reference=args.reference, pass_calls=False)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/MetaSV-0.5-py2.7.egg/metasv/generate_final_vcf.py", line 435, in convert_metasv_bed_to_vcf
    interval_info = get_interval_info(interval,pass_calls)
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/MetaSV-0.5-py2.7.egg/metasv/generate_final_vcf.py", line 77, in get_interval_info
    info.update(json.loads(base64.b64decode(feature.fields[10])))
  File "/mnt/galaxyTools/tools/pymodules/python2.7/lib/python/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by dauss75** [comment]
FYI, my colleague who uses metasv .3 ran the same data and did not encounter the error.

**Comment by marghoob** [comment]
Thanks for bringing this up, @dauss75 . Did you try running MetaSV version 0.5.3? It does have some bugfixes. Please let me know if 0.5.3 gives the same error for you.

**Comment by dauss75** [comment]
Thanks for the note. I thought I was using 0.5.3, but was not. The latest version fixes the error!

**Comment by marghoob** [comment]
No worries! I am glad the issue was fixed.
