### ISSUE TITLE
pybedtools.helpers.BEDToolsError: missing bed file

### ISSUE THREAD

**Issue by Gabby1210** [bioinform/metasv#116]
Hi,

I want to detect deletion only.This is my command:
run_metasv.py --reference ../data/MIC_supercont_chr_combine.txt --breakdancer_native ./BDcaller/version1/BD/CU427_EC_chr_BD --pindel_native ./BDcaller/version1/pindel/CU427_D --sample WT --bam ../data/CU427_chr_EC_bwa_sorted.bam --spades spades.py --age age_align --num_threads 4 --workdir work --outdir DEL --isize_mean 236.88 --isize_sd 172.95 --svs_to_assemble DEL --svs_to_report DEL

The error messange:
Traceback (most recent call last):
  File "/usr/local/bin/run_metasv.py", line 143, in <module>
    sys.exit(run_metasv(args))
  File "/usr/local/lib/python2.7/dist-packages/metasv/main.py", line 338, in run_metasv
    convert_metasv_bed_to_vcf(bedfile=genotyped_bed, vcf_out=final_vcf, workdir=args.workdir, sample=args.sample, reference=args.reference, pass_calls=False)
  File "/usr/local/lib/python2.7/dist-packages/metasv/generate_final_vcf.py", line 573, in convert_metasv_bed_to_vcf
    filterd_bed = filter_confused_INS_calls(nonfilterd_bed, filterd_bed)
  File "/usr/local/lib/python2.7/dist-packages/metasv/generate_final_vcf.py", line 164, in filter_confused_INS_calls
    bad_INS = bedtool_INS.window(bedtool_bp_nonINS, w=wiggle)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 664, in decorated
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/bedtool.py", line 243, in wrapped
    check_stderr=check_stderr)
  File "/usr/local/lib/python2.7/dist-packages/pybedtools/helpers.py", line 423, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError: 
Command was:

	bedtools window -w 20 -b /root/work/genotyping/pybedtools.WpFB8r.tmp -a /root/work/genotyping/pybedtools.rfbScw.tmp

Error message was:
Error: The requested bed file (/root/work/genotyping/pybedtools.rfbScw.tmp) could not be opened. Exiting!

I am not sure what's the problem, please let me know if there is anything I can do. Thank you!

**Comment by Gabby1210** [comment]
Hi,

I change the pyvcf into version 0.6.7 and also the bedtools into 2.26, and everything is fixed.

**Comment by marghoob** [comment]
Thanks @Gabby1210 for letting us know of the fixed. I am glad you were able to get it running!
