### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'cnvnator.call'

### ISSUE THREAD

**Issue by colinhercus** [bioinform/metasv#125]
Hi,

I installed metasv using pip install and when I run it I get a missing file cnvnator.call. Full log is below signature.

Thanks, Colin

run_metasv.py --reference /wd5/sq/grch37decoy/hs37d5.000.fa --breakdancer_native breakdancer.out --breakseq_native breakseq.gff --cnvnator_native cnvnator.call --pindel_native pindel_D pindel_LI pindel_SI pindel_TD pindel_INV --bam chimera.bam --spades SPAdes/spades.py --age AGE/age_align --num_threads 11 --workdir work --outdir out --max_ins_intervals 500000 --isize_mean 500 --isize_sd 150 --sample 1
INFO 2018-02-01 15:07:02,114 metasv.main          Running MetaSV 0.5.2
INFO 2018-02-01 15:07:02,114 metasv.main          Command-line /st2/colin/.local/bin/run_metasv.py --reference /wd5/sq/grch37decoy/hs37d5.000.fa --breakdancer_native breakdancer.out --breakseq_native breakseq.gff --cnvnator_native cnvnator.call --pindel_native pindel_D pindel_LI pindel_SI pindel_TD pindel_INV --bam chimera.bam --spades SPAdes/spades.py --age AGE/age_align --num_threads 11 --workdir work --outdir out --max_ins_intervals 500000 --isize_mean 500 --isize_sd 150 --sample 1
INFO 2018-02-01 15:07:02,114 metasv.main          Arguments are Namespace(age='AGE/age_align', age_timeout=300, age_window=20, assembly_max_tools=1, assembly_pad=500, bams=['chimera.bam'], boost_sc=False, breakdancer_native=['breakdancer.out'], breakdancer_vcf=[], breakseq_native=['breakseq.gff'], breakseq_vcf=[], chromosomes=[], cnvkit_vcf=[], cnvnator_native=['cnvnator.call'], cnvnator_vcf=[], disable_assembly=False, enable_per_tool_output=False, extraction_max_read_pairs=10000, filter_gaps=False, gaps=None, gatk_vcf=[], gt_normal_frac=0.05, gt_window=100, inswiggle=100, isize_mean=500.0, isize_sd=150.0, keep_standard_contigs=False, lumpy_vcf=[], manta_vcf=[], max_ins_cov_frac=1.5, max_ins_intervals=500000, max_nm=10, maxsvlen=1000000, mean_read_coverage=50, mean_read_length=100, min_avg_base_qual=20, min_del_subalign_len=50, min_ins_cov_frac=0.5, min_inv_subalign_len=50, min_mapq=5, min_matches=50, min_soft_clip=20, min_support_frac_ins=0.05, min_support_ins=15, minsvlen=50, num_threads=11, outdir='out', overlap_ratio=0.5, pindel_native=['pindel_D', 'pindel_LI', 'pindel_SI', 'pindel_TD', 'pindel_INV'], pindel_vcf=[], reference='/wd5/sq/grch37decoy/hs37d5.000.fa', sample='1', sc_other_scale=5, spades='SPAdes/spades.py', spades_max_interval_size=50000, spades_options='', spades_timeout=300, stop_spades_on_fail=False, svs_to_assemble=set(['DUP', 'INV', 'DEL', 'INS']), svs_to_report=set(['INV', 'CTX', 'INS', 'DEL', 'ITX', 'DUP']), svs_to_softclip=set(['DUP', 'INV', 'DEL', 'INS']), wham_vcf=[], wiggle=100, workdir='work')
INFO 2018-02-01 15:07:02,115 metasv.main          Only SVs on the following contigs will be reported: ['GL000191.1', 'GL000192.1', 'GL000193.1', 'GL000194.1', 'GL000195.1', 'GL000196.1', 'GL000197.1', 'GL000198.1', 'GL000199.1', 'GL000200.1', 'GL000201.1', 'GL000202.1', 'GL000203.1', 'GL000204.1', 'GL000205.1', 'GL000206.1', 'GL000207.1', 'GL000208.1', 'GL000209.1', 'GL000210.1', 'GL000211.1', 'GL000212.1', 'GL000213.1', 'GL000214.1', 'GL000215.1', 'GL000216.1', 'GL000217.1', 'GL000218.1', 'GL000219.1', 'GL000220.1', 'GL000221.1', 'GL000222.1', 'GL000223.1', 'GL000224.1', 'GL000225.1', 'GL000226.1', 'GL000227.1', 'GL000228.1', 'GL000229.1', 'GL000230.1', 'GL000231.1', 'GL000232.1', 'GL000233.1', 'GL000234.1', 'GL000235.1', 'GL000236.1', 'GL000237.1', 'GL000238.1', 'GL000239.1', 'GL000240.1', 'GL000241.1', 'GL000242.1', 'GL000243.1', 'GL000244.1', 'GL000245.1', 'GL000246.1', 'GL000247.1', 'GL000248.1', 'GL000249.1', 'NC_007605', 'chr1', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr2', 'chr20', 'chr21', 'chr22', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chrM', 'chrX', 'chrY', 'hs37d5']
INFO 2018-02-01 15:07:02,115 metasv.main          Load native files
INFO 2018-02-01 15:07:02,115 metasv.cnvnator_reader File is cnvnator.call
Traceback (most recent call last):
  File "/st2/colin/.local/bin/run_metasv.py", line 143, in <module>
    sys.exit(run_metasv(args))
  File "/home/colin/.local/lib/python2.7/site-packages/metasv/main.py", line 106, in run_metasv
    for record in svReader(native_file, svs_to_report=args.svs_to_report):
  File "/home/colin/.local/lib/python2.7/site-packages/metasv/cnvnator_reader.py", line 110, in __init__
    self.file_fd = open(file_name)
IOError: [Errno 2] No such file or directory: 'cnvnator.call'

**Comment by msahraeian** [comment]
Thanks for using MetaSV @colinhercus. Would you please make sure you have the cnvnator prediction file cnvnator.call in your system. The argument to "--cnvnator_native" should point to that file.

**Comment by zlye** [comment]
Hi I am having the same problem - could you explain what the the 'cnvnator.call' file? what should I expect to find it? Is this something that should be generated before running metaSV?

**Comment by marghoob** [comment]
Hi @zlye , the 'cnvnator.call' file is the output of running CNVnator (this is the native non-VCF output from `cnvnator call`) and is generated before running MetaSV. Multiple SV calling tools need to be run before their output is provided to MetaSV for integration.
