### ISSUE TITLE
type 'exceptions.IOError': Broken pipe

### ISSUE THREAD

**Issue by songtaogui** [bioinform/metasv#126]
Hi,
I'm running metaSV with cmd like:

`run_metasv.py --reference /home/gst/work/ref/Zea_mays.AGPv4.dna.toplevel.fa --boost_sc --pindel_vcf Q417_pindel.vcf --breakdancer_vcf Q417_breakdancer.vcf --cnvnator_native Q417_cnvnator.out --manta_vcf Q417_manta.vcf --lumpy_vcf Q417_lumpy.vcf --wham_vcf Q417_whamg.vcf --mean_read_length 150 --sample Q417 --bam /home/gst/work/b73_BWAMEM_bam/Q417_bwa/Q417.bwamem.sort.bam --spades ~/gst/sftw/SPAdes-3.11.1-Linux/bin/spades.py --age ~/gst/sftw/anaconda2/bin/age_align --num_threads 8 --workdir work --outdir out --min_support_ins 4 --max_ins_intervals 500000 --isize_mean 350 --isize_sd 50`

and it breaked with error said:

> INFO 2018-07-10 02:09:14,322 parallel_generate_sc_intervals-<_MainProcess(MainProcess, started)> Selecting the top 500000 intervals based on normalized read support
> INFO 2018-07-10 02:12:48,947 parallel_generate_sc_intervals-<_MainProcess(MainProcess, started)> After merging with work/metasv.bed 124230 features
> <type 'exceptions.IOError'>: Broken pipe
> The command was:
> 
>         bedtools sort -i stdin
> 
> Things to check:
> Traceback (most recent call last):
>   File "/home/gst/sftw/anaconda2/bin/run_metasv.py", line 143, in <module>
>     sys.exit(run_metasv(args))
>   File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/metasv/main.py", line 292, in run_metasv
>     other_scale=args.sc_other_scale)
>   File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/metasv/generate_sv_intervals.py", line 1165, in parallel_generate_sc_intervals
>     bedtool = bedtool.each(partial(fix_precise_coords)).sort().saveas(interval_bed)
>   File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/pybedtools/bedtool.py", line 668, in decorated
>     result = method(self, *args, **kwargs)
>   File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/pybedtools/bedtool.py", line 243, in wrapped
>     check_stderr=check_stderr)
>   File "/home/gst/sftw/anaconda2/lib/python2.7/site-packages/pybedtools/helpers.py", line 456, in call_bedtools
>     print '\n\t' + '\n\t'.join(problems[err.errno])
> KeyError: 32

What's the cause of  this error? 

Thank you!

best wishes,

songtao gui

**Comment by marghoob** [comment]
Hi @songtaogui what version of bedtools are you using? Do you have the complete log?

**Comment by songtaogui** [comment]
I used bedtools v2.25.0, and please find attached the complete log. Is it something wrong with the bedtools I used?  I'll update bedtools and try again.
Thank you for your reply.
[run_metaSV.log2.gz](https://github.com/bioinform/metasv/files/2186781/run_metaSV.log2.gz)
