### ISSUE TITLE
metasv error when running local assembly

### ISSUE THREAD

**Issue by amaiacc** [bioinform/metasv#83]
Hi Brad,

I found a problem with metaSV when running the local assembly - Spades. 
It seems a similar error to: https://github.com/chapmanb/bcbio-nextgen/issues/1075, but I'm not sure about what is causing the problem.
Please find the error copied below.

Thanks,
amaia

```
INFO 2015-12-16 10:43:31,315 metasv.run_spades    5176 intervals selected
INFO 2015-12-16 10:43:31,315 metasv.run_spades    22 intervals ignored
INFO 2015-12-16 10:43:32,807 run_spades_single-<Process(PoolWorker-2, started daemon)> Processing interval 22   16054689        16054690        eyJOVU1fU1ZNRVRIT0RTIjogMSwgIkJEX1NDT1JFIjogMzUuMCwgIkJEX09SSTIiOiAiMTQrMTMtIiwgIkJEX1BPUzEiOiAxNjA1NDY4OCwgIkJEX1BPUzIiOiAxNjA1NDgyOSwgIkJEX09SSTEiOiAiMTQrMTMtIiwgIkJEX0NIUjEiOiAiMjIiLCAiU09VUkNFUyI6ICIyMi0xNjA1NDY4OS0xNjA1NDY4OS0xMjQtQnJlYWtEYW5jZXIiLCAiQkRfQ0hSMiI6ICIyMiIsICJOVU1fU1ZUT09MUyI6IDEsICJCRF9TVVBQT1JUSU5HX1JFQURfUEFJUlMiOiA0fQ==,INS,124,RP   1       .
INFO 2015-12-16 10:43:32,808 extract_read_pairs-<Process(PoolWorker-2, started daemon)> Extracting reads from /data/corpora/MPI_workspace/lag/workspaces/lg-ngs/working//bam_sort/DYS14587.final.sorted.bam for region 22:16054689-16054690 with padding 500 using functions ['all_pair', 'non_perfect']
ERROR 2015-12-16 10:43:32,909 run_spades_single-<Process(PoolWorker-2, started daemon)> Caught exception in worker thread
Traceback (most recent call last):
  File "/home/amacar/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 68, in run_spades_single
    max_read_pairs=max_read_pairs, sv_type=sv_type)
  File "/home/amacar/.local/lib/python2.7/site-packages/metasv/extract_pairs.py", line 93, in extract_read_pairs
    aln_list = [aln for aln in bam.fetch(chr_name, start=chr_start, end=chr_end) if not aln.is_secondary]
  File "csamtools.pyx", line 1059, in pysam.csamtools.Samfile.fetch (pysam/csamtools.c:12490)
  File "csamtools.pyx", line 989, in pysam.csamtools.Samfile._parseRegion (pysam/csamtools.c:11668)
  File "csamtools.pyx", line 923, in pysam.csamtools.Samfile.gettid (pysam/csamtools.c:10827)
  File "csamtools.pyx", line 57, in pysam.csamtools._force_bytes (pysam/csamtools.c:3393)
TypeError: Expected bytes, got unicode
INFO 2015-12-16 10:43:33,066 metasv.run_spades    Merging the contigs from []
Traceback (most recent call last):
  File "/data/corpora/MPI_workspace/lag/workspaces/lg-ngs/working/programs/metasv-0.4/scripts/run_metasv.py", line 136, in <module>
    sys.exit(run_metasv(args))
  File "/home/amacar/.local/lib/python2.7/site-packages/metasv/main.py", line 307, in run_metasv
    assembly_max_tools=args.assembly_max_tools)
  File "/home/amacar/.local/lib/python2.7/site-packages/metasv/run_spades.py", line 204, in run_spades_parallel
    for line in fileinput.input(assembly_fastas):
  File "/usr/lib64/python2.7/fileinput.py", line 253, in next
    line = self.readline()
  File "/usr/lib64/python2.7/fileinput.py", line 346, in readline
    self._buffer = self._file.readlines(self._bufsize)
```

**Comment by marghoob** [comment]
Thanks @amaiacc for filing this issue. Which version of pysam are you using? Looks like @chapmanb 's fix either did not go through or was overridden accidentally.

**Comment by chapmanb** [comment]
amaia -- thanks for the report and sorry about the problem. It looks like I missed a place where we needed to explicitly change the chromosome to be a string instead of unicode before feeding to pysam. I sent in a PR, and also pushed a new conda version of metasv with this fix in bioconda (https://bioconda.github.io/) so you could get it right away with:
```
conda install -c bioconda metasv
```
Thanks again for reporting this.
